### PR TITLE
Adding/var/log/cloudify to stdout.

### PR DESCRIPTION
**Pull request by bartoszkosciug**

### CODE REVIEW

**Review by yuvlar — COMMENTED** [review]
LGTM, though I'm still not sure we need to make it a default.
We can put a conditional to all of this.

@bartoszkosciug How does the logs in DataDog look with that configuration, is it readable?

**Comment by bartoszkosciug** [comment]
> LGTM, though I'm still not sure we need to make it a default. We can put a conditional on all of this.
> 
> @bartoszkosciug How do the logs in DataDog look with that configuration, is it readable?



> LGTM, though I'm still not sure we need to make it a default. We can put a conditional on all of this.
> 
> @bartoszkosciug How do the logs in DataDog look with that configuration, is it readable?

image

**Comment by yuvlar** [comment]
I didn't expect the logs to show before every log line from which log file it is.
If that's how it works, I'm fine with pushing it - but still unsure if we want it by default.
@tikhon-opsfleet @alexmolev , What do you think?

**Review by yuvlar — DISMISSED** [review]
Alex approved it as default behaviour for the chart.
Let's wait for Tikhon's approval as well for the code part, then merge.
Next week we'll promote a patch version and apply it to the SaaS

**Comment by yuvlar** [comment]
@bartoszkosciug Please see Tikhon's suggestion.
I actually liked the pre-line which indicates which log file is it, but if it can be done in the beginning of the log line itself that's even better cause it'll be easier for filtering.
Please see what you can do

**Comment by bartoszkosciug** [comment]
> @bartoszkosciug Please see Tikhon's suggestion. I actually liked the pre-line which indicates which log file is it, but if it can be done in the beginning of the log line itself that's even better cause it'll be easier for filtering. Please see what you can do

image
image

**Review by yuvlar — APPROVED** [review]
Looks good.
Well done Bartosz, the logs in DD look great.
Please wait for @tikhon-opsfleet approval as well for merge

**Review by tikhon-opsfleet — APPROVED** [review]
Looks great, approved.

**Pull request merged**
